site_name: OpenSimula

theme:
    name: "material"
    logo: img/logo_opensimula.png
    palette:
        primary: indigo

plugins:
    - search
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      show_source: false

nav:
    - OpenSimula: index.md
    - Getting started: getting_started.md
    - API Reference: reference.md
