# Componentes generados automáticamente desde DXF
# Espacios: 6
# Building_surface EXTERIOR:    26
# Building_surface INTERIOR:    16  ← paredes medianeras detectadas
# Building_surface UNDERGROUND: 6  ← soleras
#
# COMPLETAR antes de usar:
#   spaces_type   → Space_type de cada zona
#   construction  → construcción real de cada superficie
#   ground_material → material de terreno en soleras UNDERGROUND

dxf_components = [
        {
            "type": "Space",
            "name": "P2_1",
            "building": "edificio",
            "spaces_type": "not_defined",
            "floor_area": 16.2037,
            "volume": 48.6111,
            "furniture_weight": 10,
        },
        {
            "type": "Building_surface",
            "name": "P2_1_wall_0",
            "shape": "RECTANGLE",
            "width": 2.965,
            "height": 3.0,
            "ref_point": [0.0, -0.0, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1"],
        },
        {
            "type": "Building_surface",
            "name": "P2_1_wall_1",
            "shape": "RECTANGLE",
            "width": 3.5,
            "height": 3.0,
            "ref_point": [2.965, -0.0, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1"],
        },
        {
            "type": "Building_surface",
            "name": "P2_1_wall_2",
            "shape": "RECTANGLE",
            "width": 1.965,
            "height": 3.0,
            "ref_point": [2.965, 3.5, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1"],
        },
        {
            "type": "Building_surface",
            "name": "P2_1_wall_3",
            "shape": "RECTANGLE",
            "width": 2.965,
            "height": 3.0,
            "ref_point": [2.965, 5.465, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_1_wall_4",
            "shape": "RECTANGLE",
            "width": 5.465,
            "height": 3.0,
            "ref_point": [0.0, 5.465, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1"],
        },
        {
            "type": "Building_surface",
            "name": "P2_1_roof",
            "shape": "POLYGON",
            "x_polygon": [0.0, 2.965, 2.965, 2.965, 0.0],
            "y_polygon": [-0.0, -0.0, 3.5, 5.465, 5.465],
            "ref_point": [0.0, 0.0, 3.0],
            "azimuth": 0,
            "altitude": 90,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1"],
        },
        {
            "type": "Building_surface",
            "name": "P2_1_floor",
            "shape": "POLYGON",
            "x_polygon": [0.0, 2.965, 2.965, 2.965, 0.0],
            "y_polygon": [-0.0, -0.0, 3.5, 5.465, 5.465],
            "ref_point": [0.0, 0.0, 0.0],
            "azimuth": 0,
            "altitude": -90,
            "surface_type": "UNDERGROUND",
            "construction": "not_defined",
            "ground_material": "not_defined",
            "spaces": ["P2_1"],
        },
        {
            "type": "Space",
            "name": "P2_2",
            "building": "edificio",
            "spaces_type": "not_defined",
            "floor_area": 7.1726,
            "volume": 21.5178,
            "furniture_weight": 10,
        },
        {
            "type": "Building_surface",
            "name": "P2_2_wall_0",
            "shape": "RECTANGLE",
            "width": 2.07,
            "height": 3.0,
            "ref_point": [2.965, -0.0, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2"],
        },
        {
            "type": "Building_surface",
            "name": "P2_2_wall_1",
            "shape": "RECTANGLE",
            "width": 3.465,
            "height": 3.0,
            "ref_point": [5.035, -0.0, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2", "P2_3"],
        },
        {
            "type": "Building_surface",
            "name": "P2_2_wall_2",
            "shape": "RECTANGLE",
            "width": 2.07,
            "height": 3.0,
            "ref_point": [5.035, 3.465, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_2_wall_3",
            "shape": "RECTANGLE",
            "width": 3.465,
            "height": 3.0,
            "ref_point": [2.965, 3.465, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2"],
        },
        {
            "type": "Building_surface",
            "name": "P2_2_roof",
            "shape": "POLYGON",
            "x_polygon": [2.965, 5.035, 5.035, 2.965],
            "y_polygon": [-0.0, -0.0, 3.465, 3.465],
            "ref_point": [0.0, 0.0, 3.0],
            "azimuth": 0,
            "altitude": 90,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2"],
        },
        {
            "type": "Building_surface",
            "name": "P2_2_floor",
            "shape": "POLYGON",
            "x_polygon": [2.965, 5.035, 5.035, 2.965],
            "y_polygon": [-0.0, -0.0, 3.465, 3.465],
            "ref_point": [0.0, 0.0, 0.0],
            "azimuth": 0,
            "altitude": -90,
            "surface_type": "UNDERGROUND",
            "construction": "not_defined",
            "ground_material": "not_defined",
            "spaces": ["P2_2"],
        },
        {
            "type": "Space",
            "name": "P2_3",
            "building": "edificio",
            "spaces_type": "not_defined",
            "floor_area": 10.1524,
            "volume": 30.4572,
            "furniture_weight": 10,
        },
        {
            "type": "Building_surface",
            "name": "P2_3_wall_0",
            "shape": "RECTANGLE",
            "width": 2.93,
            "height": 3.0,
            "ref_point": [5.035, -0.0, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_3"],
        },
        {
            "type": "Building_surface",
            "name": "P2_3_wall_1",
            "shape": "RECTANGLE",
            "width": 3.465,
            "height": 3.0,
            "ref_point": [7.965, -0.0, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_3", "P2_4"],
        },
        {
            "type": "Building_surface",
            "name": "P2_3_wall_2",
            "shape": "RECTANGLE",
            "width": 2.93,
            "height": 3.0,
            "ref_point": [7.965, 3.465, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_3", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_3_wall_3",
            "shape": "RECTANGLE",
            "width": 3.465,
            "height": 3.0,
            "ref_point": [5.035, 3.465, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2", "P2_3"],
        },
        {
            "type": "Building_surface",
            "name": "P2_3_roof",
            "shape": "POLYGON",
            "x_polygon": [5.035, 7.965, 7.965, 5.035],
            "y_polygon": [-0.0, -0.0, 3.465, 3.465],
            "ref_point": [0.0, 0.0, 3.0],
            "azimuth": 0,
            "altitude": 90,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_3"],
        },
        {
            "type": "Building_surface",
            "name": "P2_3_floor",
            "shape": "POLYGON",
            "x_polygon": [5.035, 7.965, 7.965, 5.035],
            "y_polygon": [-0.0, -0.0, 3.465, 3.465],
            "ref_point": [0.0, 0.0, 0.0],
            "azimuth": 0,
            "altitude": -90,
            "surface_type": "UNDERGROUND",
            "construction": "not_defined",
            "ground_material": "not_defined",
            "spaces": ["P2_3"],
        },
        {
            "type": "Space",
            "name": "P2_4",
            "building": "edificio",
            "spaces_type": "not_defined",
            "floor_area": 32.4463,
            "volume": 97.3389,
            "furniture_weight": 10,
        },
        {
            "type": "Building_surface",
            "name": "P2_4_wall_0",
            "shape": "RECTANGLE",
            "width": 6.535,
            "height": 3.0,
            "ref_point": [7.965, -0.0, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4"],
        },
        {
            "type": "Building_surface",
            "name": "P2_4_wall_1",
            "shape": "RECTANGLE",
            "width": 4.965,
            "height": 3.0,
            "ref_point": [14.5, -0.0, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4"],
        },
        {
            "type": "Building_surface",
            "name": "P2_4_wall_2",
            "shape": "RECTANGLE",
            "width": 6.535,
            "height": 3.0,
            "ref_point": [14.5, 4.965, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_4_wall_3",
            "shape": "RECTANGLE",
            "width": 1.5,
            "height": 3.0,
            "ref_point": [7.965, 4.965, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_4_wall_4",
            "shape": "RECTANGLE",
            "width": 3.465,
            "height": 3.0,
            "ref_point": [7.965, 3.465, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_3", "P2_4"],
        },
        {
            "type": "Building_surface",
            "name": "P2_4_roof",
            "shape": "POLYGON",
            "x_polygon": [7.965, 14.5, 14.5, 7.965, 7.965],
            "y_polygon": [-0.0, -0.0, 4.965, 4.965, 3.465],
            "ref_point": [0.0, 0.0, 3.0],
            "azimuth": 0,
            "altitude": 90,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4"],
        },
        {
            "type": "Building_surface",
            "name": "P2_4_floor",
            "shape": "POLYGON",
            "x_polygon": [7.965, 14.5, 14.5, 7.965, 7.965],
            "y_polygon": [-0.0, -0.0, 4.965, 4.965, 3.465],
            "ref_point": [0.0, 0.0, 0.0],
            "azimuth": 0,
            "altitude": -90,
            "surface_type": "UNDERGROUND",
            "construction": "not_defined",
            "ground_material": "not_defined",
            "spaces": ["P2_4"],
        },
        {
            "type": "Space",
            "name": "P2_5",
            "building": "edificio",
            "spaces_type": "not_defined",
            "floor_area": 44.2975,
            "volume": 132.8925,
            "furniture_weight": 10,
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_0",
            "shape": "RECTANGLE",
            "width": 2.965,
            "height": 3.0,
            "ref_point": [0.0, 5.465, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_1", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_1",
            "shape": "RECTANGLE",
            "width": 2.0,
            "height": 3.0,
            "ref_point": [2.965, 5.465, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_2",
            "shape": "RECTANGLE",
            "width": 2.07,
            "height": 3.0,
            "ref_point": [2.965, 3.465, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_2", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_3",
            "shape": "RECTANGLE",
            "width": 2.93,
            "height": 3.0,
            "ref_point": [5.035, 3.465, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_3", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_4",
            "shape": "RECTANGLE",
            "width": 1.5,
            "height": 3.0,
            "ref_point": [7.965, 3.465, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_5",
            "shape": "RECTANGLE",
            "width": 6.535,
            "height": 3.0,
            "ref_point": [7.965, 4.965, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_4", "P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_6",
            "shape": "RECTANGLE",
            "width": 3.0,
            "height": 3.0,
            "ref_point": [14.5, 4.965, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_7",
            "shape": "RECTANGLE",
            "width": 6.5,
            "height": 3.0,
            "ref_point": [14.5, 7.965, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5", "P2_6"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_8",
            "shape": "RECTANGLE",
            "width": 0.465,
            "height": 3.0,
            "ref_point": [8.0, 7.965, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_9",
            "shape": "RECTANGLE",
            "width": 1.0,
            "height": 3.0,
            "ref_point": [8.0, 7.5, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_10",
            "shape": "RECTANGLE",
            "width": 1.5,
            "height": 3.0,
            "ref_point": [8.0, 6.5, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_11",
            "shape": "RECTANGLE",
            "width": 1.0,
            "height": 3.0,
            "ref_point": [6.5, 6.5, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_12",
            "shape": "RECTANGLE",
            "width": 6.5,
            "height": 3.0,
            "ref_point": [6.5, 7.5, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_wall_13",
            "shape": "RECTANGLE",
            "width": 2.035,
            "height": 3.0,
            "ref_point": [0.0, 7.5, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_roof",
            "shape": "POLYGON",
            "x_polygon": [0.0, 2.965, 2.965, 5.035, 7.965, 7.965, 14.5, 14.5, 8.0, 8.0, 8.0, 6.5, 6.5, 0.0],
            "y_polygon": [5.465, 5.465, 3.465, 3.465, 3.465, 4.965, 4.965, 7.965, 7.965, 7.5, 6.5, 6.5, 7.5, 7.5],
            "ref_point": [0.0, 0.0, 3.0],
            "azimuth": 0,
            "altitude": 90,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Building_surface",
            "name": "P2_5_floor",
            "shape": "POLYGON",
            "x_polygon": [0.0, 2.965, 2.965, 5.035, 7.965, 7.965, 14.5, 14.5, 8.0, 8.0, 8.0, 6.5, 6.5, 0.0],
            "y_polygon": [5.465, 5.465, 3.465, 3.465, 3.465, 4.965, 4.965, 7.965, 7.965, 7.5, 6.5, 6.5, 7.5, 7.5],
            "ref_point": [0.0, 0.0, 0.0],
            "azimuth": 0,
            "altitude": -90,
            "surface_type": "UNDERGROUND",
            "construction": "not_defined",
            "ground_material": "not_defined",
            "spaces": ["P2_5"],
        },
        {
            "type": "Space",
            "name": "P2_6",
            "building": "edificio",
            "spaces_type": "not_defined",
            "floor_area": 19.7275,
            "volume": 59.1825,
            "furniture_weight": 10,
        },
        {
            "type": "Building_surface",
            "name": "P2_6_wall_0",
            "shape": "RECTANGLE",
            "width": 6.5,
            "height": 3.0,
            "ref_point": [8.0, 7.965, 0.0],
            "azimuth": 0.0,
            "altitude": 0,
            "surface_type": "INTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_5", "P2_6"],
        },
        {
            "type": "Building_surface",
            "name": "P2_6_wall_1",
            "shape": "RECTANGLE",
            "width": 3.035,
            "height": 3.0,
            "ref_point": [14.5, 7.965, 0.0],
            "azimuth": 90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_6"],
        },
        {
            "type": "Building_surface",
            "name": "P2_6_wall_2",
            "shape": "RECTANGLE",
            "width": 6.5,
            "height": 3.0,
            "ref_point": [14.5, 11.0, 0.0],
            "azimuth": 180.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_6"],
        },
        {
            "type": "Building_surface",
            "name": "P2_6_wall_3",
            "shape": "RECTANGLE",
            "width": 3.035,
            "height": 3.0,
            "ref_point": [8.0, 11.0, 0.0],
            "azimuth": -90.0,
            "altitude": 0,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_6"],
        },
        {
            "type": "Building_surface",
            "name": "P2_6_roof",
            "shape": "POLYGON",
            "x_polygon": [8.0, 14.5, 14.5, 8.0],
            "y_polygon": [7.965, 7.965, 11.0, 11.0],
            "ref_point": [0.0, 0.0, 3.0],
            "azimuth": 0,
            "altitude": 90,
            "surface_type": "EXTERIOR",
            "construction": "not_defined",
            "spaces": ["P2_6"],
        },
        {
            "type": "Building_surface",
            "name": "P2_6_floor",
            "shape": "POLYGON",
            "x_polygon": [8.0, 14.5, 14.5, 8.0],
            "y_polygon": [7.965, 7.965, 11.0, 11.0],
            "ref_point": [0.0, 0.0, 0.0],
            "azimuth": 0,
            "altitude": -90,
            "surface_type": "UNDERGROUND",
            "construction": "not_defined",
            "ground_material": "not_defined",
            "spaces": ["P2_6"],
        },
]